### ISSUE TITLE
大佬 请教下 这个 KCMaxSectionCount 到底是做什么用的

### ISSUE THREAD

**Issue by ZsIsMe** [ac1217/KCBannerView#1]

**Comment by ac1217** [comment]
就是让整个collectionView有多个分组而已，每次滚到中间的分组就可以实现左右循环滑动了，这个值随便给个100，1000也可以

**Comment by ZsIsMe** [comment]
多谢回复 这个值只要不越界多大都关系？
我想问下为什么不是3？这个值小了有什么影响么

**Comment by ac1217** [comment]
3也可以阿，只不过就是随便滑动记下就能滑到边界了，值越大就越难滑到边界，而且每次用户停止滑动的时候又会重置到中间的分组，这样就让人觉得永远滑不到尽头

**Comment by ZsIsMe** [comment]
明白
